[workspace]

members = [
    "proto/BonusAufgabe_proto",
    "proto/Aufgabe4",
    "proto/Aufgabe3",
    "proto/BonusAufgabe_distributed",
    "proto/Bonusaufgabe"
]

exclude = [
    "Aufgaben/Aufgabe3",
    "Aufgaben/Bonusaufgabe"
]